### ISSUE TITLE
Simplify and improve Post block

### ISSUE THREAD

**Issue by perandre** [front/gutenberg#1]
I would like to make the Post block even more intuitive:

1. Make title text Settings "L" size as default
2. Remove Drop Cap setting
3. Remove Background Color
4. Remove Bold/Italics/Strikethrough/Link (I see that bolding and italics can be useful, but not the others. I assume here link is not needed; it should go to the post).
5. Remove Text align options (let's leave that for the theme)
6. Add toggle: Show/Hide image
7. Decrease the line-height proportionally to size. It should be 1.2.

A choice needs to be made; we need to separate two post blocks: a) Manually positioned article and b) Auto article (last from x category). OR it could be the same block type, but with some kind of toggle (toggle auto mode true/false). What do you think?

**Comment by SofiaSousa** [comment]
I think we can have 3 types of Posts:
- Auto post
- Post with id
- Static post

The **Auto post** is the last post of all or the last from a category. Only a ref (and category) will be saved. The post content (title, image, link, etc) is dynamic and could change everytime it is rendered.

The **Post with id** is similar to auto post but for a specific post. The *post_id* will be saved and everytime the post is rendered, a request should be done to get the post content, keeping it always updated.  

For the **Static post** there is no dyamic content, the user must insert the content of the post manually (title, image, link, etc) and this is what will be rendered.

A **Post with id** could easly be converted into a **Static post** (if the title or image must be changed, for example).

And those 3 types could be implement in the same block. Some extra attributes are needed to control what should be saved and rendered.
